version: "3.9"

services:
  application:
    container_name: application
    build: ./backend
    ports:
      - "9000:9000"
    depends_on:
      - redis_database
    environment:
      REDIS_HOST: redis_database
      REDIS_PORT: 6379
      
  redis_database:
      container_name: redis
      image: redis:alpine3.16
      ports:
        - "6379:6379"