services:
  - type: web
    name: application
    repo: https://github.com/warengeorge/Full-Stack-Recipe-Management-System
    buildFilter:
      paths:
        - ./backend/**
    buildCommand: cd backend npm install
    startCommand: cd backend npm start
    runtime: node
    plan: free
    # connect to the redis_database service
    
    # depends_on:
      - redis_database
    environment:
      REDIS_HOST: redis_database
      REDIS_PORT: 6379

  - type: redis
    ipAllowList: []
    name: redis_database
    plan: free