services:
  - type: web
    name: application
    repo: https://github.com/warengeorge/Full-Stack-Recipe-Management-System
    buildFilter:
      paths:
        - ./backend/**
    buildCommand: cd backend npm install
    startCommand: cd backend npm start
    runtime: node
    plan: free

  - type: redis
    ipAllowList: []
    name: redis_database
    plan: free